### ISSUE TITLE
Merge into JuliaGraphs

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/GraphDataFrameBridge.jl#1]
@sbromberger OK, I think this is now a full repo (albeit a thin one for the moment) -- tests, readme, etc. Looks like I need a promotion in `JuliaGraphs` to transfer ownership. That something you could help with?

**Comment by sbromberger** [comment]
Very cool! Yes. I can help with this on Sunday or Monday. Are you available to chat on slack sometime during the mornings Pacific time?

**Comment by nickeubank** [comment]
Sounds good! I’ll look for you AM pacific time.

**Comment by sbromberger** [comment]
Hey - if you're around now, hop on slack.

**Comment by nickeubank** [comment]
Not around a computer till tomorrow sorry.

**Comment by sbromberger** [comment]
No worries. Talk to you tomorrow.

**Comment by sbromberger** [comment]
Closing out since we seem to have done this?
