### ISSUE TITLE
Publishing updated version

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/GraphDataFrameBridge.jl#12]
@sbromberger @jpfairbanks 

Hey all -- I'm afraid I've been out of the julia ecosystem for a while (big year of teaching, which sadly has pulled me back into Python), and it appears that the package publishing system has changed (`attobot` is dead?!). Would one of you kindly point me to the current best way to publish the updated version of GraphDataFrameBridge? Just merged some tweaks to keep up with dataframes.

**Comment by jpfairbanks** [comment]
I think it was replaced by Registrator 


https://github.com/JuliaRegistries/Registrator.jl

**Comment by nickeubank** [comment]
Success! Thanks @jpfairbanks
