### ISSUE TITLE
Deprecation warning with DataFrames.jl

### ISSUE THREAD

**Issue by lassepe** [JuliaGraphs/GraphDataFrameBridge.jl#14]
When using GraphDataFrameBridge.jl with the latest version of DataFrames.jl (v0.21.0) there are a couple of deprecation warnings:

```julia
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = metagraph_from_dataframe(::Type{T} where T, ::DataFrame, ::Symbol, ::Symbol, ::Symbol, ::Array{Symbol,1}) at GraphDataFrameBridge.jl:92
└ @ GraphDataFrameBridge ~/.julia/packages/GraphDataFrameBridge/azYpc/src/GraphDataFrameBridge.jl:92
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = metagraph_from_dataframe(::Type{T} where T, ::DataFrame, ::Symbol, ::Symbol, ::Symbol, ::Array{Symbol,1}) at GraphDataFrameBridge.jl:92
└ @ GraphDataFrameBridge ~/.julia/packages/GraphDataFrameBridge/azYpc/src/GraphDataFrameBridge.jl:92
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = metagraph_from_dataframe(::Type{T} where T, ::DataFrame, ::Symbol, ::Symbol, ::Symbol, ::Array{Symbol,1}) at GraphDataFrameBridge.jl:97
└ @ GraphDataFrameBridge ~/.julia/packages/GraphDataFrameBridge/azYpc/src/GraphDataFrameBridge.jl:97
┌ Warning: inner joining data frames using join is deprecated, use `innerjoin(df1, df2, on=user_a, makeunique=false, validate=(false, false))` instead
│   caller = ip:0x0
└ @ Core :-1
```

**Comment by lassepe** [comment]
Never mind. I just realized this is already fixed in the master, just not released yet.

**Comment by nickeubank** [comment]
Actually that's helpful, thanks @lassepe . I actually *thought* I'd released the updated version, but apparently I failed (this is my first release since they re-worked the julia package system, so still working things out...)

**Comment by nickeubank** [comment]
@lassepe can you confirm the version of GraphDataFrameBridge you have installed using?

**Comment by lassepe** [comment]
I saw these deprecation warnings with GraphDataFrameBridge v0.2.1, when checking out the master branch, things work for me.

Though one quick comment as you are about to tag a new release: Is there a reason that DataFrames compatibility is set to
```
[compat]
DataFrames = "0.20.0, 2.0.0"
```
From my understanding this results in a compatibility with `[0.20.0-0.20.1, 2.0.0-3.0.0]` (see [here](https://julialang.github.io/Pkg.jl/v1/compatibility/index.html)). Is this what was intended or should this rather be a `>=0.20`? For example, DataFrames.jl has release 0.21.0 now and this is excluded by the current compat settings.

**Comment by nickeubank** [comment]
OK, yeah, I see: `pkg` still installing GraphDataFrameBridge v0.2.1. Thanks, I'll track it down.

**Comment by nickeubank** [comment]
Yeah, I think you're right, it's a compatibility mistake. I'll track it down and ping you. The new package system doesn't seem to actually accept the inequalities, so I had to change it, and I think you're right I did it wrong. :)

**Comment by nickeubank** [comment]
It was indeed the issue with versions starting with 0. Looks like you should get version 0.2.4 if you update in Pkg now.

**Comment by lassepe** [comment]
Yes, can confirm. Seems to work!
