### ISSUE TITLE
Name field should be indexed by default

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/GraphDataFrameBridge.jl#9]
Since this package interprets string columns for source and destination vertices as a string properties with key `name`, should it index that field be default?

**Comment by nickeubank** [comment]
Good call!

**Comment by jpfairbanks** [comment]
I also think the name to integer mapping code should go in MetaGraphs because it is really useful even if you aren't using DataFrames.

**Comment by nickeubank** [comment]
@jpfairbanks for the name to integer mapping code, what input data would you want it to work for?

**Comment by jpfairbanks** [comment]
An edge list where the vertices are strings like `Vector{Tuple{String, String}}` or more abstractly `AbstractArray{Tuple{V,W}, 1} where V,W <: AbstractString`.

**Comment by jpfairbanks** [comment]
An edge list where the vertices are strings like `Vector{Tuple{String, String}}` or more abstractly `AbstractArray{Tuple{V,W}, 1} where V,W <: AbstractString`.

**Comment by nickeubank** [comment]
I see -- same basic structure, just not a dataframe?

**Comment by jpfairbanks** [comment]
Yeah this came up because I was writing a test case for MetaGraphs.jl and wanted to import the graph from a dataframe, but couldn't use the Bridge code without introducing a circular dependency.

So it would be nice to at least be able to make graphs from Iterables of tuples without using the DataFrames library. Maybe this is a case for the Tables.jl approach of "a table is an iterator over named tuples". And we just make MetaGraphs support Tables.jl tables.
